### ISSUE TITLE
we need parsing *.uvmpw file

### ISSUE THREAD

**Issue by PurplePopo** [jacksonjim/keil-assistant#10]
多工程项目真的不支持吗？
*.uvmpw 的xml文件好解析的多，真的不打算支持吗？

**Comment by jacksonjim** [comment]
目前暂时不支持，这个可以做为后续的目标，或是你帮慢做解析好这块合并进来也可以的

**Comment by jacksonjim** [comment]
已经解决，你可以试用下，目前可能功能不是很完善
