### ISSUE TITLE
更新之后build 会卡在Start to Build target

### ISSUE THREAD

**Issue by shishirong** [jacksonjim/keil-assistant#11]

**Comment by jacksonjim** [comment]
你需要重新设置下MDK路径，为了部分人需要，增加了MDK C51 C251的独立设置，调整下这块原来的需要更新下设置路径

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
