### ISSUE TITLE
编译信息的实时显示问题

### ISSUE THREAD

**Issue by AthenaMaster** [jacksonjim/keil-assistant#12]
在原作的1.7版本中，编译文件的话他的编译信息会在输出窗口实时动态显示，但是在当前版本中，只有编译完了，编译信息一口气显示。这个问题是否可以修复

**Comment by AthenaMaster** [comment]
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/95b6dcdd-db01-47d9-9a55-2f5fe0dd5204)

**Comment by AthenaMaster** [comment]
我目前有一个比较粗糙的做法，把1.7版本的通过Uv4Caller.exe的编译模式添加回来，在设置里面添加一个选项，去选择编译模式是当前的异步编译还是原本的插件编译。
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/4cbab9c6-2613-4e44-8c43-4db95fac9fb3)
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/29224f38-6833-401b-9710-c4e2bb41f1db)

**Comment by jacksonjim** [comment]
> 我目前有一个比较粗糙的做法，把1.7版本的通过Uv4Caller.exe的编译模式添加回来，在设置里面添加一个选项，去选择编译模式是当前的异步编译还是原本的插件编译。 ![image](https://user-images.githubusercontent.com/46912201/277608428-4cbab9c6-2613-4e44-8c43-4db95fac9fb3.png) ![image](https://user-images.githubusercontent.com/46912201/277608694-29224f38-6833-401b-9710-c4e2bb41f1db.png)

目前是去除那个exe主要是为后面做一些新功能有关的，目前已经调整输出log现象，你可以试用下

**Comment by AthenaMaster** [comment]
我看了一下，现在这个版本有些BUG，log日志会存在重复输出的现象。
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/30f52aff-60a1-49e3-95e1-b43e7f57f4fb)

**Comment by AthenaMaster** [comment]
还有一个点不知是否可以优化，在Keil中如果有编译错误的行号，双击即可到达行号的位置。但是这个插件的编译log中，应该是不符合vscode跳转的规范，他并不能Crtl健+行号信息进行跳转。他好像是识别相对路径或者是绝对路径进行跳转，这边要改的话可能会比较麻烦。
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/8b15ac27-1f71-49eb-844d-3e076e513df2)
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/eee4023b-df01-4e5d-bf35-00511bbb000e)

**Comment by AthenaMaster** [comment]
这边可能需要在他最开始的XML配置文件中把每个文件的路径解析出来，在编译信息的log中，查找warning，error之类的错误信息，把前面的文件名替换成相对或者绝对路径，会比较麻烦。

**Comment by jacksonjim** [comment]
> 还有一个点不知是否可以优化，在Keil中如果有编译错误的行号，双击即可到达行号的位置。但是这个插件的编译log中，应该是不符合vscode跳转的规范，他并不能Crtl健+行号信息进行跳转。他好像是识别相对路径或者是绝对路径进行跳转，这边要改的话可能会比较麻烦。 ![image](https://user-images.githubusercontent.com/46912201/277619299-8b15ac27-1f71-49eb-844d-3e076e513df2.png) ![image](https://user-images.githubusercontent.com/46912201/277619824-eee4023b-df01-4e5d-bf35-00511bbb000e.png)

 这个问题，比较麻烦的，除非输出信息是调试窗口才可以识别，本身Keil输出txt文本信息的

**Comment by jacksonjim** [comment]
> 这边可能需要在他最开始的XML配置文件中把每个文件的路径解析出来，在编译信息的log中，查找warning，error之类的错误信息，把前面的文件名替换成相对或者绝对路径，会比较麻烦。

你可以帮想想看，原本是txt文本信息不是固有格式，不太好识别，你帮忙想想看，也可以的，重复信息是vscode一个bug，已经做了clear但是还是会带出来的

**Comment by AthenaMaster** [comment]
我测试过来发现不知道是不是因为异步操作的问题，我注释掉这句话的话，他的clear函数就可以正常清除输出的内容了。
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/53ffb806-f7f3-4285-8ee1-a74e7026dee3)
我猜想应该是clear只能清除某个线程中的内容，在其他线程调用的话把所有的历史记录都打印出来了，这边检测文件变化可以不用异步操作吗

**Comment by AthenaMaster** [comment]
> > 这边可能需要在他最开始的XML配置文件中把每个文件的路径解析出来，在编译信息的log中，查找warning，error之类的错误信息，把前面的文件名替换成相对或者绝对路径，会比较麻烦。
> 
> 你可以帮想想看，原本是txt文本信息不是固有格式，不太好识别，你帮忙想想看，也可以的，重复信息是vscode一个bug，已经做了clear但是还是会带出来的

我这边大致有头绪，我去写写这边的代码，对TS不是很熟，不一定可以写出来

**Comment by AthenaMaster** [comment]
增加了log中的文件链接修改，以及高亮显示。
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/5629feb0-d395-4093-baa1-3eb8d6c0af45)
