### ISSUE TITLE
armclang6 较新版本 获取内置宏的正确参数

### ISSUE THREAD

**Issue by hellowoad** [jacksonjim/keil-assistant#13]
根椐ac6手册：https://developer.arm.com/documentation/dui0774/l/Compiler-Command-line-Options/-E?lang=en
可以看到新版本的armclang 在获取内置宏时的参数有变化：因些下面的代码在新版本的armclang上不能正确地获取内置宏

https://github.com/jacksonjim/keil-assistant/blob/182e7110a95a1843fb86b9e4188cb1c3de093d4f/src/extension.ts#L1297

我自己修改为https://github.com/hellowoad/keil-assistant/blob/ed39b72f09ced1d17b8cdb2177d7e97e87fbbec1/src/extension.ts#L1327C111-L1327C111
但是我对 ts不熟悉，使用了写死的参数，希望可以根据armclang 的版本和项目参数，自动生成对应的参数

**Comment by jacksonjim** [comment]
可以的，我来合并一起

**Comment by jacksonjim** [comment]
已经合并了，你可以尝试下，如果有特殊的mcu型号不识别话到时提供下
