### ISSUE TITLE
设置添加选项启用详细构建输出

### ISSUE THREAD

**Issue by hathlife** [jacksonjim/keil-assistant#17]
希望能在插件设置界面多添加一个选项启用详细构建输出方便按warning提示优化代码。

**Comment by jacksonjim** [comment]
> 希望能在插件设置界面多添加一个选项启用详细构建输出方便按warning提示优化代码。

目前的log与keil 的保持一样的，这个log本身也是keil的，不明白你所需的详细相相构建的输出是需要在哪里设置的参数，麻烦指出下，[UV4 的命令参数](https://www.keil.com/support/man/docs/uv4cl/uv4cl_ui_project.htm ) 你可以从中的指出下所需的参数，我来帮你在设置中添加对应选项

**Comment by PR2403** [comment]
> > 希望能在插件设置界面多添加一个选项启用详细构建输出方便按warning提示优化代码。
> 
> 目前的log与keil 的保持一样的，这个log本身也是keil的，不明白你所需的详细相相构建的输出是需要在哪里设置的参数，麻烦指出下，[UV4 的命令参数](https://www.keil.com/support/man/docs/uv4cl/uv4cl_ui_project.htm) 你可以从中的指出下所需的参数，我来帮你在设置中添加对应选项
这是keil的输出
![image](https://github.com/jacksonjim/keil-assistant/assets/64511917/733343e9-774b-4c47-9851-f178eed3e406)
这是vscode的输出
![image](https://github.com/jacksonjim/keil-assistant/assets/64511917/05c34f0a-aa5a-4e7b-b1e0-de9f6988960d)

**Comment by PR2403** [comment]
这些信息都是编译器和链接器的，keil应该不会回显这些信息。不过用vscode编辑后再用keil编译就行了

**Comment by jacksonjim** [comment]
> 这些信息都是编译器和链接器的，keil应该不会回显这些信息。不过用vscode编辑后再用keil编译就行了

有输出的这些log的，你目前用哪个版本的，我查看下，具体情况，或是你编译的项目是arm还是C51?

**Comment by PR2403** [comment]
> > 这些信息都是编译器和链接器的，keil应该不会回显这些信息。不过用vscode编辑后再用keil编译就行了
> 
> 有输出的这些log的，你目前用哪个版本的，我查看下，具体情况，或是你编译的项目是arm还是C51?

![image](https://github.com/jacksonjim/keil-assistant/assets/64511917/32b0661b-ce0e-4d98-9597-71693529a5af)
ARM
你用的是keil的命令行，这些信息都是编译器和链接器的，keil没有回显这些信息。我用的另外一个构建系统也是不会回显

**Comment by jacksonjim** [comment]
![image](https://github.com/jacksonjim/keil-assistant/assets/3296695/18f8658a-d6c1-4b31-a2b3-0eadfd89ea27)
这是我这边测试的，都有显示出来！可能与你项目有一定关系吧

**Comment by jacksonjim** [comment]
> > > 这些信息都是编译器和链接器的，keil应该不会回显这些信息。不过用vscode编辑后再用keil编译就行了
> > 
> > 
> > 有输出的这些log的，你目前用哪个版本的，我查看下，具体情况，或是你编译的项目是arm还是C51?
> 
> ![image](https://private-user-images.githubusercontent.com/64511917/286066203-32b0661b-ce0e-4d98-9597-71693529a5af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTY0MDAsIm5iZiI6MTcwMTE1NjEwMCwicGF0aCI6Ii82NDUxMTkxNy8yODYwNjYyMDMtMzJiMDY2MWItY2UwZS00ZDk4LTk1OTctNzE2OTM1MjlhNWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA3MjE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzM2JhMjhkYWQ2MGE3NTZlODEzMTlmMmFkM2YxNWI0NTc5Yzg2ZGJmOTRkYmM3ZWI3MDc3OTc4MDRkNzczMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._xoFCcGvcgf9bbN1KMSvx4Peyfwghl0_i9ifxBX3s-o) ARM 你用的是keil的命令行，这些信息都是编译器和链接器的，keil没有回显这些信息。我用的另外一个构建系统也是不会回显

命令行是有回显示的，输出对应的log文件，你添加一个路径就可以保存输出的Log了

**Comment by jacksonjim** [comment]
另外如果还有异常可以查看下你项目的目录下的.vscode目录中是否有生成uv4.log 文件，检查下内容是否为最新的

**Comment by PR2403** [comment]
我现在测试可以了，怪了我啥也没动。算了就先这样吧

**Comment by jacksonjim** [comment]
> 我现在测试可以了，怪了我啥也没动。算了就先这样吧

最新版本已经优化下log输出，晚些你更新下
