### ISSUE TITLE
dowmload快捷键支持设置成F8

### ISSUE THREAD

**Issue by Nydxsst** [jacksonjim/keil-assistant#18]
首先非常感谢维护插件，当前的dowm快捷键是Ctrl+Alt+D，能否支持设置成keil的默认快捷键F8，比较符合使用习惯

**Comment by AthenaMaster** [comment]
点击ctrl + shift + p，输入download to device
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/80c6911e-8005-4910-afe6-9cd604a04a5d)
输入你想要的快捷键，比如F8,按回车就可以了，这个是直接vscode改快捷键，不需要插件的配合
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/31570121-c63f-4ea8-a7ab-bc61e3228b8e)

**Comment by jacksonjim** [comment]
> 首先非常感谢维护插件，当前的dowm快捷键是Ctrl+Alt+D，能否支持设置成keil的默认快捷键F8，比较符合使用习惯

这个目前是使用原作者的的配置，暂时没有计划改变这个习惯，目前大多数人沿用原来的快捷键，如果大多数人有这个需要话，再统一修改相关的快捷键控制。你可以参考楼上暂时设置为你喜欢的快捷键，后续如果有更多人提出这个需求，再来变更掉这个

**Comment by Nydxsst** [comment]
感谢两位解答，已使用vscode修改快捷键为F8
