### ISSUE TITLE
项目中没有导入 rte 包， 错误的引入了 __rte__ 宏

### ISSUE THREAD

**Issue by hellowoad** [jacksonjim/keil-assistant#19]
__rte__ 这个宏是一直引入的吗 我的项目在keil中没有勾选任何rte，__rte__也被引入了

**Comment by jacksonjim** [comment]
目前是根据*.uvprojx文件中是否包括了<RTE> 这个标记。按理应该不是引入这个RTE的。你给我一个.uvprojx文件参考下

**Comment by jacksonjim** [comment]
后面改进下这识别的项
