### ISSUE TITLE
是否可以添加设置项目编码选项

### ISSUE THREAD

**Issue by AthenaMaster** [jacksonjim/keil-assistant#21]
在keil中通常使用GB2312编码格式，但是VSCode中通常是UTF-8。如果是修改VSCode的编码格式，会导致兼容性不好，也尝试过将vscode的编码格式修改为自动，但是并不是特别智能。
 ```
async setEncoding() {
        if (workspace.workspaceFolders && workspace.workspaceFolders.length > 0) {
            // 项目根目录
            const workspace_dir = workspace.workspaceFolders[0].uri.fsPath;

            // .vscode目录路径
            const vscode_dir = workspace_dir + "\\" + ".vscode";
            console.log(vscode_dir);

            // 在项目根目录下创建一个.vscode子目录
            if (!fs.existsSync(vscode_dir))
                fs.mkdirSync(vscode_dir);

            // 创建.vscode/c_cpp_properties.json文件
            const c_cpp_properties_file = vscode_dir + "\\" + "settings.json";
            fs.writeFileSync(c_cpp_properties_file, JSON.stringify({ "files.encoding": "gb2312" }, null, 2), { mode: 0o644 });
        }

    }
 ```
之前我在自己的代码中添加了这样的一个指令，来设置项目的编码格式，感觉非常好用。但是版本迭代后不会使用分支合并上去，这边可以添加一下吗
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/66c6b760-b8c0-432f-96ad-9de1a1217445)

**Comment by AthenaMaster** [comment]
以及还有一个问题，就是插件生成的c_cpp_properties.json，我觉得是放在项目文件的根目录下面的vscode是一个更好的选择，vscode，并不会去检测uvoptx的目录，只会找根目录的.vscode文件夹路径。当前我是手动复制的，这样项目基本不会出现波浪线报错，宏定义也全部都能找到。
![image](https://github.com/jacksonjim/keil-assistant/assets/46912201/371cd6fa-6f65-4196-9d81-3e4557f62ee6)

**Comment by jacksonjim** [comment]
> 以及还有一个问题，就是插件生成的c_cpp_properties.json，我觉得是放在项目文件的根目录下面的vscode是一个更好的选择，vscode，并不会去检测uvoptx的目录，只会找根目录的.vscode文件夹路径。当前我是手动复制的，这样项目基本不会出现波浪线报错，宏定义也全部都能找到。 ![image](https://private-user-images.githubusercontent.com/46912201/286650596-371cd6fa-6f65-4196-9d81-3e4557f62ee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MjYwNDMsIm5iZiI6MTcwMTgyNTc0MywicGF0aCI6Ii80NjkxMjIwMS8yODY2NTA1OTYtMzcxY2Q2ZmEtNmY2NS00MTk2LTlkODEtM2U0NTU3ZjYyZWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAxMjIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5NGM2ZWNjMjQ3NWUxZjdhMDI3NGVmNzY3YmJjY2ZlMGFhOTMwMDVlNWVhY2E1NjU0ZTEzYzJiNGM0NDJjNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVTm6XLpmu3YA_41zEeE8G37u4V9zt4uW_sywA_TZ-U)

这个.vscode是根据项目所在目录中创建，目前有个冲突点是应用多个项目下，会出现冲突，你帮想想看有没有更好的处理方式，之前做单个项目是没什么问题的，都可以根据对应位置创建.vscode
