### ISSUE TITLE
加载Keil项目以后不能切换工作区

### ISSUE THREAD

**Issue by yxf-ahpu** [jacksonjim/keil-assistant#23]
配置如下：
版本: 1.84.2 (system setup)
提交: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
日期: 2023-11-09T10:51:52.184Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631

加载Keil项目，会提示切换工作区，确认以后无法切换工作区

**Comment by jacksonjim** [comment]
你能提供详细说问题点不，比如操作方式和截图一起配合
