### ISSUE TITLE
每次重新打开vscode会导致c_cpp_properties.json被重置

### ISSUE THREAD

**Issue by PR2403** [jacksonjim/keil-assistant#24]
keil5的一些中间件不会在项目的.c .h里出现
![image](https://github.com/jacksonjim/keil-assistant/assets/64511917/f98a8e3a-2b54-4f96-952f-1d57e258ef73)
keil会在编译时添加这些，但不会在项目设置里出现
所有我会手动修改c_cpp_properties.json，但每次重新打开vscode都会导致它被重置
能否不要每次重置c_cpp_properties.json

**Comment by jacksonjim** [comment]
cmsis 默认部分会加载，你手动在keil添加的include也会加载的，我手上的项目都是有手动添加include都可以添加的。目前每次打开vscode重置c_cpp_properties.json 是为了同步在keil做的修改，重新加载用的！

**Comment by PR2403** [comment]
> cmsis 默认部分会加载，你手动在keil添加的include也会加载的，我手上的项目都是有手动添加include都可以添加的。目前每次打开vscode重置c_cpp_properties.json 是为了同步在keil做的修改，重新加载用的！

所以在keil里手动再添加一遍include？麻烦了一点，不过就先这样吧

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
