### ISSUE TITLE
插件好像不能实现错误警告的跳转

### ISSUE THREAD

**Issue by JudeWinton** [jacksonjim/keil-assistant#25]
有警告不能跳转到警告代码的那一行

**Comment by jacksonjim** [comment]
是在哪里提示警告的行信息，给个详细点说明，我看看是否可以增加

**Comment by aycma** [comment]
Keil Assistant v1.7.0有这个功能,出现错误警告,按Ctrl+鼠标左键,可以快速跳转到错误行.
