### ISSUE TITLE
尝试导入了一个STC32项目，提示：检测到#include错误。请更新includePath。

### ISSUE THREAD

**Issue by Alaye-Dong** [jacksonjim/keil-assistant#26]
![image](https://github.com/jacksonjim/keil-assistant/assets/123649770/73be1cbd-a519-45a7-9887-2443b86cb200)
如图，是哪里还没有设置对吗，这个includePath是哪个地方的，求助，感谢。

**Comment by jacksonjim** [comment]
你这个headfile.h在哪个目录，另外查看下keil中配置的include路径是否有包含，如果有话应该是没问题，或你上传c_cpp_properties.json 这个文件和*..uvproj

**Comment by jacksonjim** [comment]
还有就是你这个乱码问题，你把右下角的utf-8选择为gb232或gbk

**Comment by zeroL-C** [comment]
我的也是这样，麻烦看一下我的路径。
工程报错：
![image](https://github.com/jacksonjim/keil-assistant/assets/56534589/51117af5-f185-4ac3-8956-b58ea4a1cb0a)
工程路径：D:\SynologyDrive\HC32F460_原厂移植\库版本2.2.0\example\ev_hc32f460_lqfp100_v2\sdioc\sd_multi_write_multi_read_4bit_25mhz\MDK
![image](https://github.com/jacksonjim/keil-assistant/assets/56534589/62c46634-68e4-4127-8b00-0df1ae290c09)
报错文件路径：D:\SynologyDrive\HC32F460_原厂移植\库版本2.2.0\midware\sd_card\inc
![image](https://github.com/jacksonjim/keil-assistant/assets/56534589/d5151099-536d-4086-9481-286eda7dabbf)
C的配置文件json：
![image](https://github.com/jacksonjim/keil-assistant/assets/56534589/789d052f-6f62-44d1-85ad-9649d4518317)

**Comment by jacksonjim** [comment]
> 我的也是这样，麻烦看一下我的路径。 工程报错： ![image](https://private-user-images.githubusercontent.com/56534589/295480360-51117af5-f185-4ac3-8956-b58ea4a1cb0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI0NjcsIm5iZiI6MTcwNDk0MjE2NywicGF0aCI6Ii81NjUzNDU4OS8yOTU0ODAzNjAtNTExMTdhZjUtZjE4NS00YWMzLTg5NTYtYjU4ZWE0YTFjYjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NGJhMGNkZGFjOWNmMDRkMDdkODM2NWJlYzM3N2Y2ZDEzMmQ3ZDk0YTZiOTJlYmYwYWI5OTE0N2NhYThhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lra6Sod7vSgq2tTlLU91GMtUXRXLfcUHx1ww96IRTS0) 工程路径：D:\SynologyDrive\HC32F460_原厂移植\库版本2.2.0\example\ev_hc32f460_lqfp100_v2\sdioc\sd_multi_write_multi_read_4bit_25mhz\MDK ![image](https://private-user-images.githubusercontent.com/56534589/295480907-62c46634-68e4-4127-8b00-0df1ae290c09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI0NjcsIm5iZiI6MTcwNDk0MjE2NywicGF0aCI6Ii81NjUzNDU4OS8yOTU0ODA5MDctNjJjNDY2MzQtNjhlNC00MTI3LThiMDAtMGRmMWFlMjkwYzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYWI4MWVhMjlhYmUxNjE5ZmMzOGNkZWViMWIzMmExN2M1Nzc5OWZhZWQ2ZTBkMWZkNTFkNWNlMTk0MjY1ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zm1SZ7cuK-KNDjOR50k5t3tjI8Sbim6CjVx81VopdqY) 报错文件路径：D:\SynologyDrive\HC32F460_原厂移植\库版本2.2.0\midware\sd_card\inc ![image](https://private-user-images.githubusercontent.com/56534589/295481170-d5151099-536d-4086-9481-286eda7dabbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI0NjcsIm5iZiI6MTcwNDk0MjE2NywicGF0aCI6Ii81NjUzNDU4OS8yOTU0ODExNzAtZDUxNTEwOTktNTM2ZC00MDg2LTk0ODEtMjg2ZWRhN2RhYmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMWY2ZDVhY2RiNzYwZTllYjM3NWFhMmIxYWM0YjBiZDVmYjhlMzY4ZTk4ZDA5MGI5ODU5YjJhMzViNzBiYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h43sZRtEZ6uu8hrSNCP1O-PyimGT-fzp-MmTJXGz1rg) C的配置文件json： ![image](https://private-user-images.githubusercontent.com/56534589/295481520-789d052f-6f62-44d1-85ad-9649d4518317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI0NjcsIm5iZiI6MTcwNDk0MjE2NywicGF0aCI6Ii81NjUzNDU4OS8yOTU0ODE1MjAtNzg5ZDA1MmYtNmY2Mi00NGQxLTg1YWQtOTY0OWQ0NTE4MzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NGVjNzg2ODhkY2RlYTI4Mjk5MzNmYjkyM2M1YzVkMGVjODBmNzFlYzQ3N2I3NTdjMzFiMjFhNzRiOGE1MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._hdtPLqH8z75oHOkWiexx0-5PPCtqgU71LD5s3Sn9HE)

我刚刚模拟下你这个路径，测试下也没有问题，不会提示，按ctrl+点击也可以打开对应的路径，我创建的路径中也有中文，

**Comment by zeroL-C** [comment]
> > 我的也是这样，麻烦看一下我的路径。 工程报错： ![image](https://private-user-images.githubusercontent.com/56534589/295480360-51117af5-f185-4ac3-8956-b58ea4a1cb0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI0NjcsIm5iZiI6MTcwNDk0MjE2NywicGF0aCI6Ii81NjUzNDU4OS8yOTU0ODAzNjAtNTExMTdhZjUtZjE4NS00YWMzLTg5NTYtYjU4ZWE0YTFjYjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NGJhMGNkZGFjOWNmMDRkMDdkODM2NWJlYzM3N2Y2ZDEzMmQ3ZDk0YTZiOTJlYmYwYWI5OTE0N2NhYThhNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lra6Sod7vSgq2tTlLU91GMtUXRXLfcUHx1ww96IRTS0) 工程路径：D:\SynologyDrive\HC32F460_原厂移植\库版本2.2.0\example\ev_hc32f460_lqfp100_v2\sdioc\sd_multi_write_multi_read_4bit_25mhz\MDK ![image](https://private-user-images.githubusercontent.com/56534589/295480907-62c46634-68e4-4127-8b00-0df1ae290c09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI0NjcsIm5iZiI6MTcwNDk0MjE2NywicGF0aCI6Ii81NjUzNDU4OS8yOTU0ODA5MDctNjJjNDY2MzQtNjhlNC00MTI3LThiMDAtMGRmMWFlMjkwYzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzYWI4MWVhMjlhYmUxNjE5ZmMzOGNkZWViMWIzMmExN2M1Nzc5OWZhZWQ2ZTBkMWZkNTFkNWNlMTk0MjY1ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zm1SZ7cuK-KNDjOR50k5t3tjI8Sbim6CjVx81VopdqY) 报错文件路径：D:\SynologyDrive\HC32F460_原厂移植\库版本2.2.0\midware\sd_card\inc ![image](https://private-user-images.githubusercontent.com/56534589/295481170-d5151099-536d-4086-9481-286eda7dabbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI0NjcsIm5iZiI6MTcwNDk0MjE2NywicGF0aCI6Ii81NjUzNDU4OS8yOTU0ODExNzAtZDUxNTEwOTktNTM2ZC00MDg2LTk0ODEtMjg2ZWRhN2RhYmJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMWY2ZDVhY2RiNzYwZTllYjM3NWFhMmIxYWM0YjBiZDVmYjhlMzY4ZTk4ZDA5MGI5ODU5YjJhMzViNzBiYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h43sZRtEZ6uu8hrSNCP1O-PyimGT-fzp-MmTJXGz1rg) C的配置文件json： ![image](https://private-user-images.githubusercontent.com/56534589/295481520-789d052f-6f62-44d1-85ad-9649d4518317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDI0NjcsIm5iZiI6MTcwNDk0MjE2NywicGF0aCI6Ii81NjUzNDU4OS8yOTU0ODE1MjAtNzg5ZDA1MmYtNmY2Mi00NGQxLTg1YWQtOTY0OWQ0NTE4MzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDAzMDI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NGVjNzg2ODhkY2RlYTI4Mjk5MzNmYjkyM2M1YzVkMGVjODBmNzFlYzQ3N2I3NTdjMzFiMjFhNzRiOGE1MTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._hdtPLqH8z75oHOkWiexx0-5PPCtqgU71LD5s3Sn9HE)
> 
> 我刚刚模拟下你这个路径，测试下也没有问题，不会提示，按ctrl+点击也可以打开对应的路径，我创建的路径中也有中文， ![image](https://private-user-images.githubusercontent.com/3296695/295779036-154b3a7e-85e6-4587-a662-ee0a50b72bb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDM1ODksIm5iZiI6MTcwNDk0MzI4OSwicGF0aCI6Ii8zMjk2Njk1LzI5NTc3OTAzNi0xNTRiM2E3ZS04NWU2LTQ1ODctYTY2Mi1lZTBhNTBiNzJiYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDMyMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTVhOTFkYjY4NGMzMGExZWVhNmRlNDNkMTg4ZjhmMzBiZGJiOGU3NzZjNGVmZTgyYjJjNDZhMDlhYmQyMWJmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wwWEa6jg6WAt7Kw5pE8P_c8egD4uc599CzCvpbcK5N0) ![image](https://private-user-images.githubusercontent.com/3296695/295779119-eb987fbc-3e76-49f0-bb1a-6116e2ec2c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDM1ODksIm5iZiI6MTcwNDk0MzI4OSwicGF0aCI6Ii8zMjk2Njk1LzI5NTc3OTExOS1lYjk4N2ZiYy0zZTc2LTQ5ZjAtYmIxYS02MTE2ZTJlYzJjMTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDMyMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTQ1OWZkNTJmMmY4YTgwMjY4ZmM1NmMxZmZjOTM0YWNiOGI3YWUwODA0ZjkzOGMyZjMwNWU3YjcwNjNjMTU4MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gQ6xuabh7HBh2P8Ga0h2zAdfX3cM3oLmv6YKkOIkShc) ![image](https://private-user-images.githubusercontent.com/3296695/295779176-c564fabf-3bb1-46b4-947d-8b3a9986d884.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDM1ODksIm5iZiI6MTcwNDk0MzI4OSwicGF0aCI6Ii8zMjk2Njk1LzI5NTc3OTE3Ni1jNTY0ZmFiZi0zYmIxLTQ2YjQtOTQ3ZC04YjNhOTk4NmQ4ODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDMyMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMzZWFmODY2OTU1MGEwZTZhYTg2ZWY0ODkxNWRkNzM0ZjdiOGEwNmQzNmQ2Mzk0Y2ExNDRmODliYWZjYzI0YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KkuIKCk3Azs0zp2uYWwxDb_2kb8mnPzMaVpgOcEKEnQ) ![image](https://private-user-images.githubusercontent.com/3296695/295779357-ac28f208-6700-482b-978c-8ea72f5facb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDM1ODksIm5iZiI6MTcwNDk0MzI4OSwicGF0aCI6Ii8zMjk2Njk1LzI5NTc3OTM1Ny1hYzI4ZjIwOC02NzAwLTQ4MmItOTc4Yy04ZWE3MmY1ZmFjYjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDMyMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2EwMjY4ZjIxNDdjMmJlNTBlYTRlN2M5MDQxYmY2ZjY0NzUwYjU3OTFjMDM1OTg4YWZmNWZlMzZjMDE2Mjc3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RZgfrCnnzxF7yp75fXQEHcZy6YSNucsl2b5HhFUIKls)
> 
> 我的添加这个文件引用方式是直接在keil上添加的，你可以参考下 ![image](https://private-user-images.githubusercontent.com/3296695/295779538-9fe360f1-7759-486d-a45b-fad043fd6002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NDM1ODksIm5iZiI6MTcwNDk0MzI4OSwicGF0aCI6Ii8zMjk2Njk1LzI5NTc3OTUzOC05ZmUzNjBmMS03NzU5LTQ4NmQtYTQ1Yi1mYWQwNDNmZDYwMDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDMyMTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODE5NDcxN2EzZjg0NmI4Mjg1OGQ2ZGViOTY4NTk1ZWQ4Y2M0NGJmNzA1ZTQyY2ZiMTNkMDg5YWU1NDczNmZhMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qUu4UnfqOrXjnnFFEyNd6wExyutTqoVW4bRIIp7NxQ4) 如果还是不行话，你发个远程协助的方式给我，向日葵的码，你可以直接发邮件给我，定个时间我远程查看下你项目文件配置，看下具体原因是哪里引起的，我这边目前只是验证相同的路径引用，没有复现出问题

我的识别码:850218495
使用向日葵即可对我发起远程协助
向日葵下载地址:http://url.oray.com/tGJdas/
今日验证码：zu135s

**Comment by Alaye-Dong** [comment]
感谢，我仔细检查了json中引用文件的地址，进行了补全，现在已经没有了include的错误提示。但是中断isr
中又出现了问题，我按照README中在headfile中定义了interruput但是似乎无效？还是我的方式有问题？
<img width="1280" alt="image" src="https://github.com/jacksonjim/keil-assistant/assets/123649770/0208bec4-bf8e-428b-8628-6263869107e0">

**Comment by Alaye-Dong** [comment]
> 你这个headfile.h在哪个目录，另外查看下keil中配置的include路径是否有包含，如果有话应该是没问题，或你上传c_cpp_properties.json 这个文件和*..uvproj

感谢，我仔细检查了json中引用文件的地址，进行了补全，现在已经没有了include的错误提示。但是中断isr
中又出现了问题，我按照README中在headfile中定义了interruput但是似乎无效？还是我的方式有问题？
![image](https://github.com/jacksonjim/keil-assistant/assets/123649770/7b6cc6fa-0dff-454a-af18-e26169512b30)

**Comment by jacksonjim** [comment]
> > 你这个headfile.h在哪个目录，另外查看下keil中配置的include路径是否有包含，如果有话应该是没问题，或你上传c_cpp_properties.json 这个文件和*..uvproj
> 
> 感谢，我仔细检查了json中引用文件的地址，进行了补全，现在已经没有了include的错误提示。但是中断isr 中又出现了问题，我按照README中在headfile中定义了interruput但是似乎无效？还是我的方式有问题？ ![image](https://private-user-images.githubusercontent.com/123649770/295916249-7b6cc6fa-0dff-454a-af18-e26169512b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDExMTMsIm5iZiI6MTcwNTA0MDgxMywicGF0aCI6Ii8xMjM2NDk3NzAvMjk1OTE2MjQ5LTdiNmNjNmZhLTBkZmYtNDU0YS1hZjE4LWUyNjE2OTUxMmIzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNjI2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODk3YTliODc2NDQ2YWE0MjE3NmIyNDhkNjk4OGI1OTQ2ZDExMjZjZWE0MzFlMjcxODlmMTgwNGU4MjZlNTc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pokbDFPRBiOdqzXT2Nu98cGtRcxdatCT9WioXFBfwko)

你要替换下INTERLPT(4)

**Comment by jacksonjim** [comment]
参考readme的最后一部分的示例，需要在公共的头文件中加入我建议的定义，然后在代码中替换为对应INTERRUPT(4), 这样就可以解决提示的问题
