### ISSUE TITLE
编译后如果错误,输出窗口的提示错误行,没有超链接跳转跳到错误行.

### ISSUE THREAD

**Issue by aycma** [jacksonjim/keil-assistant#27]
编译后如果错误,输出窗口的提示错误行,没有超链接跳转跳到错误行.

**Comment by aycma** [comment]
Keil Assistant v1.7.0有这个功能,出现错误警告,按Ctrl+鼠标左键,可以快速跳转到错误行.

**Comment by jacksonjim** [comment]
可以给我个截图，我查看下，一起修复这个问题
或参考信息

**Comment by aycma** [comment]
在 2024-01-11 11:24:19，"jacksonjim" ***@***.***> 写道：

可以给我个截图，我查看下，一起修复这个问题
或参考信息

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件推荐客户端极速下载
QQ录屏20240111112958.mp4 (31.71M, 2024年1月26日 11:35 到期)
下载

**Comment by aycma** [comment]
演示视频已发邮箱了,你看一下

**Comment by jacksonjim** [comment]
> 演示视频已发邮箱了,你看一下

已经修复，你验证下最新版本

**Comment by aycma** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年01月20日 11:06 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jacksonjim/keil-assistant] 编译后如果错误,输出窗口的提示错误行,没有超链接跳转跳到错误行. (Issue #27) |

演示视频已发邮箱了,你看一下

已经修复，你验证下最新版本
