### ISSUE TITLE
打开工程提示open project failed !, msg: ENOENT: no such file or directory, mkdir 'undefined\.vscode'

### ISSUE THREAD

**Issue by cctv180** [jacksonjim/keil-assistant#28]
打开mdk工程文件提示open project failed !, msg: ENOENT: no such file or directory, mkdir 'undefined\.vscode'
keil-assistant插件版本是v1.9.0
vscode版本是1.85.2
工程是STM32CubeMX生成的stm32h743xi全新工程也一样提示
两台电脑升级keil-assistant插件后表现一致,经测试v1.8.9之前版本使用正常
请问要怎么操作才能用呢。

**Comment by jacksonjim** [comment]
你能给下关于你项目的目录结构，我看下你这边的情况

**Comment by cctv180** [comment]
> 你提供下关于你项目的目录结构，我看下你草莓的情况

目录结构请克隆以下仓库，或者用STM32CubeMX生成就行，下面仓库我刚拉取全新测试并安装v1.9.0可以复现标题现象
git clone https://github.com/cctv180/STM32H743XI_Demo --recursive

**Comment by jacksonjim** [comment]
你在vscode打开这个STM32H743XI_Demo这个目录就可以了，我测试下正常的能打开识别的。这个是图片就是查看的项目
![image](https://github.com/jacksonjim/keil-assistant/assets/3296695/08930614-a912-40a4-a2b5-0b5a5eed4fa9)

**Comment by cctv180** [comment]
> 你在vscode打开这个STM32H743XI_Demo这个目录就可以了，我测试下正常的能识别打开的。这个是图片就是查看的项目 ![图像](https://private-user-images.githubusercontent.com/3296695/300167908-08930614-a912-40a4-a2b5-0b5a5eed4fa9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzYyODMsIm5iZiI6MTcwNjc3NTk4MywicGF0aCI6Ii8zMjk2Njk1LzMwMDE2NzkwOC0wODkzMDYxNC1hOTEyLTQwYTQtYTJiNS0wYjVhNWVlZDRmYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDgyNjIzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU3NjY5Y2YzMmU2ZmU3MGY3MjFmMzNmMDgzOWE1YzFiNzJjNjQxZTJkYzk5MDY2ZjQwZGRkM2Y0MDM3ZmE4ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ton5Vj_11VfwZAeuhpJY7KaO2m2WUy_Q14uAxPjyzI0)

非常感谢解答，已经会用了，我之前是从KEIL UVISION项目里面开工程所以会报错。

**Comment by MyZQL** [comment]
可以通过打开文件夹导入项目，但无法通过图标按钮导入是怎么回事？

**Comment by jacksonjim** [comment]
> 可以通过打开文件夹导入项目，但无法通过图标按钮导入是怎么回事？

图标是添加自定义路径的目录，但是一般来说直接打开目录就可以了
