### ISSUE TITLE
工程文件不在文件夹根目录的时候，不太方便

### ISSUE THREAD

**Issue by shishirong** [jacksonjim/keil-assistant#3]
比如

> ├─SDK
> │  ├─lib
> │  │  └─xxx.lib
> │  ├─component
> │  │  └─...
> │  └─Templates
> │      └─project

只把project作为工作区的话，用全局搜索很不方便。将SDK+project保存为工作区，keil-assistant 又不能自动打开。

**Comment by jacksonjim** [comment]
你这个是多个工程的项目还是说单工程的多目录的，目前插件也是能支持多项目的，但是相对来说暂时可能不是很完美吧，这个是因为关系到keil 的工程文件问题，所以你能否提供更详细的需求说明，再来分析下处理这个功能

**Comment by shishirong** [comment]
我这个是单工程的项目，为了方便全局搜索只能以SDK目录为vscode工作区，每次都要手动再为`keil-assistant`选.uvprojx文件，之后keil-assistant会提示这个（switch workspace）：
![image](https://github.com/jacksonjim/keil-assistant/assets/16620315/a92fb9a6-0b6e-4e1d-9364-6e870f26727d)
以前不熟悉keil-assistant的时候会点击OK。。。

不过现在习惯了，感觉也能将就用。

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jacksonjim** [comment]
大概明白你的项目文件是放在子目录中的project下，根据之前的原创作者保留的功能只搜索 .vscode 目录所在的根目录中的*.uvprjx

**Comment by shishirong** [comment]
> 大概明白你的项目文件是放在子目录中的project下，根据之前的原创作者保留的功能只搜索 .vscode 目录所在的根目录中的*.uvprjx

是的。要是能在.vscode/keil_project_properties.json 中保存项目列表，每次能自动打开就好了

**Comment by jacksonjim** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
