### ISSUE TITLE
c_cpp_properties.json可以包含RTE的文件嗎?

### ISSUE THREAD

**Issue by gary7530** [jacksonjim/keil-assistant#30]
![image](https://github.com/jacksonjim/keil-assistant/assets/53919056/d7bad092-baef-41c2-818a-138ccc4862a6)
在VScode無法開啟RTE的.c.h

**Comment by jacksonjim** [comment]
这个c.h文件在哪里的路径，目前测试是包含rte的文件，但是不是很完全可能会漏，你提供下项目配置文件或完整工程

**Comment by gary7530** [comment]
使用mbed TLS
![image](https://github.com/jacksonjim/keil-assistant/assets/53919056/0e2b4ae4-7690-4178-a12f-3cf970e5e77e)

路徑是 C:\Users\USER\AppData\Local\Arm\Packs\ARM\mbedTLS\3.1.1\library
![image](https://github.com/jacksonjim/keil-assistant/assets/53919056/9d4a0820-8477-4cb0-adab-d17d3039ab60)

**Comment by jacksonjim** [comment]
上传你的工程文件*.uvprojx，我查看下配置信息，看看引用的路径关键信息

**Comment by gary7530** [comment]
> 上傳你的工程文件*.uvprojx，我查看下配置信息，看看引用的路徑關鍵信息

[test.zip](https://github.com/jacksonjim/keil-assistant/files/14424779/test.zip)

**Comment by jacksonjim** [comment]
检查下你手上的项目配置有个地方不对，就是版本号，不知道是不是你那手动修改的.uvprojx这个文件，所以出现你这个情况
`    <components>
      <component Cclass="Security" Cgroup="mbed TLS" Cvendor="ARM" Cversion="3.1.0">
        <package name="mbedTLS" schemaVersion="1.6.3" url="https://www.keil.com/pack/" vendor="ARM" version="3.1.1"/>
        <targetInfos>
          <targetInfo name="Target 1"/>
        </targetInfos>
      </component>
    </components>`

实际 是3.1.0你的文件是3.1.1
