### ISSUE TITLE
[建议]: 关于 Extension Pack

### ISSUE THREAD

**Issue by ShiinaKaze** [jacksonjim/keil-assistant#31]
希望将 Extension Pack 改为 [Recommended extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_recommended-extensions)

**Comment by jacksonjim** [comment]
不是很明白你的这个，这个应该是用户手册的，不是api的相关配置，[extension-pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup)， [https://code.visualstudio.com/api/references/extension-manifest](https://code.visualstudio.com/api/references/extension-manifest) 所以能否提供详细的建议

**Comment by ShiinaKaze** [comment]
> 不是很明白你的这个，这个应该是用户手册的，不是api的相关配置，[extension-pack](https://code.visualstudio.com/blogs/2017/03/07/extension-pack-roundup)， https://code.visualstudio.com/api/references/extension-manifest 所以能否提供详细的建议

就是这个 Field
![image](https://github.com/jacksonjim/keil-assistant/assets/89641145/83e23cd8-b86c-454e-b705-2b2206f9efa4)
因为卸载的时候会同时卸载 C/C++ extension，所以希望能不能改为 recommend extension
[https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions)

**Comment by jacksonjim** [comment]
你说的这个是用户端的配置，不是vs扩展配置，我看下没有你说的这个recommend extension配置项，你说的这个其实是工作空间设置，需要用户手动设置的

**Comment by jacksonjim** [comment]
目前新版本已经调整了扩展插件为依赖关系，之前使用extensionpack是为了能在卸载时同时也删除掉依赖的扩展，后期需要用户自己手动卸载附带的扩展
