### ISSUE TITLE
[建议]: 提供 ARM Compiler 5 的路径设置

### ISSUE THREAD

**Issue by ShiinaKaze** [jacksonjim/keil-assistant#32]
由于 Keil MDK 在 `5.12` 之后不再提供 ARM Compiler version 5，手动安装时需要创建目录，但目录名可能不是 `ARMCC`

**Comment by jacksonjim** [comment]
你说的这问题点好像是在Keil uVision5 里面设置的吧，一般是找到Keil uVision5的安装路径，如果手动安装话可能路径不同，默认话现在是ARMCC或ARMCLANG。编译我这边是直接调用uv4.exe
