### ISSUE TITLE
STC32中断提示问题

### ISSUE THREAD

**Issue by Alaye-Dong** [jacksonjim/keil-assistant#33]
![image](https://github.com/jacksonjim/keil-assistant/assets/123649770/63cc8c13-2213-4940-88f4-32edee49f942)
我安装README中的方式，将C251的替换代码添加到了头文件中，仍然有红波浪线提示中端错误。😥我的代码替换方式是不是有问题，我的理解可能错误了？能否麻烦给我示例一个正常的工程参考一下。🥰我的邮箱：alayevast@outlook.com

**Comment by jacksonjim** [comment]
关于 C51/C251 的中断提示问题

在代码的公共头文件中加入以下代码替换，即可
C51 代码部分
#ifndef __VSCODE_C51__
#define INTERRUPT(x) interrupt x
#else
#define INTERRUPT(x)
#endif

C251 代码部分
#ifndef __VSCODE_C251__
#define INTERRUPT(x) interrupt x
#else
#define INTERRUPT(x)
#endif



示例代码使用 也就是在你的ISR.c文件中的改写成这样的
void UART1_int(void) INTERRUPT(UART1_VECTOR)
{
    if (RI)
    {
      RI = 0;
    }

    if (TI)
    {
      TI = 0;
    }
}

**Comment by jacksonjim** [comment]
如果没有问题反馈就先关闭了

**Comment by Alaye-Dong** [comment]
![image](https://github.com/jacksonjim/keil-assistant/assets/123649770/a5db445a-7d1d-48d4-a742-66f19ec4caf6)
我按照这个方法替换了，项目可以成功编译，但在VSCode中，仍有问题错误提示
