### ISSUE TITLE
A problem opening a project generated by STM32CubeMX

### ISSUE THREAD

**Issue by Q-S-G** [jacksonjim/keil-assistant#34]
As the title says, the following error message pops up in the lower right corner when I open a Keil project:
open project failed !, msg: Cannot read properties of undefined (reading 'replace')
How can I solve this problem?

**Comment by Q-S-G** [comment]
如果作者您擅长中文的话也可以用中文回答（其实用中文更好捏）

**Comment by jacksonjim** [comment]
能否提供下项目文件结构或demo.zip

**Comment by Q-S-G** [comment]
好的，稍后回到电脑前通过邮件发给您，感谢您的及时回复🙏🏻



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 30, 2024 15:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jacksonjim/keil-assistant] A problem opening a project generatedby STM32CubeMX (Issue #34)




 
能否提供下项目文件结构或demo.zip

**Comment by Q-S-G** [comment]
您好，请允许我详细描述这个问题并附上项目压缩包。
首先，这个问题会在打开用CubeMX生成的比较复杂的工程时出现，也就是说当我打开一个标准库的工程时没有碰到过这个问题（也可能是因为我没有用标准库写过很复杂的工程），而且一些简单的CubeMX生成的HAL库工程也能正常打开，比如点亮一个LED。但是，最近我基于一块STM32G0板卡创建了一个CubeMX生成的Keil工程，刚开始（几乎没有添加任何配置时）还能用VScode的插件打开，但是配置了I2C，USART和官方例程等内容后就无法打开并出现open project: 'G0B1RE-1.uvprojx' failed !, msg: Cannot read properties of undefined (reading 'replace')错误提示。
奇怪的是，我自己尝试了包括但不限于禁用插件后重启插件，卸载插件后重新安装插件，重启电脑，重启VScode等手段后项目有很小概率能打开（但我并不能确定是哪个手段其效果了），今天上午我尝试了近一个小时才打开，然后就一直不敢关掉VScode和电脑了，如果能打开那么编译和下载等功能是正常的。
顺带一提，使用“CL”制作的“Keil Assistant”插件打开该工程也会有相同的报错。


擎天丶傲郭
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jacksonjim/keil-assistant"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月30日(星期二) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jacksonjim/keil-assistant] A problem opening a project generated by STM32CubeMX (Issue #34)





 
能否提供下项目文件结构或demo.zip
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

G0B1RE-1.zip (148.81M, 2024年05月30日 16:49 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=22386363ec798a92116c07f540610b4b1b4c5051555058554e0e015b524c5b06525e4e0505585f490108515654500e00510a5101666d3923537a5231234c084a195113635b&code=c8ccfa9d

**Comment by jacksonjim** [comment]
我先下载你的demo看下什么情况

**Comment by jacksonjim** [comment]
目前验证下，大概上问题可能是生成的一些属性丢失了，使用keil软件打开下你的工程文件保存下就正常了。我把正常的代码给你上传的下，你可以比较参考下
[testok.zip](https://github.com/jacksonjim/keil-assistant/files/15215461/testok.zip)

有差异的文件，可能是stm生成的旧版本的，目前不作任何修改只是用keil重新打开一下就可以了，
![image](https://github.com/jacksonjim/keil-assistant/assets/3296695/b926ebd0-1bd6-4b48-820d-8c616343a5ed)
另外就是你可以使用比较工具查看下我这边给你的版本的项目文件差别

**Comment by Q-S-G** [comment]
请问用Keil5.0和Keil5.3有什么区别吗？您更推荐有哪个版本呢？我之前安装的5.0，一直没升级到5.3



---Original---
From: ***@***.***&gt;
Date: Mon, May 6, 2024 10:51 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jacksonjim/keil-assistant] A problem opening a project generatedby STM32CubeMX (Issue #34)




 
目前验证下，大概上问题可能是生成的一些属性丢失了，使用keil软件打开下你的工程文件保存下就正常了。我把正常的代码给你上传的下，你可以比较参考下
 testok.zip
 
有差异的文件，可能是stm生成的旧版本的，目前不作任何修改只是用keil重新打开一下就可以了，
 image.png (view on web)
 另外就是你可以使用比较工具查看下我这边给你的版本的项目文件差别

**Comment by jacksonjim** [comment]
我目前是用最新的，这个其实没什么问题，5.0也是可以。你用它打开一次保存就可以了，然后在项目根目录用vs来打开

**Comment by jacksonjim** [comment]
现在这个问题主要是在生成的项目文件缺失一些属性

**Comment by Q-S-G** [comment]
好的，我回去了试一下，非常感谢您的帮助，后续有什么问题或者发现我会再次联系您的。



---Original---
From: ***@***.***&gt;
Date: Mon, May 6, 2024 11:26 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jacksonjim/keil-assistant] A problem opening a project generatedby STM32CubeMX (Issue #34)




 
现在这个问题主要是在生成的项目文件缺失一些属性
