### ISSUE TITLE
关于从Keil C51 的编译log跳转至对应代码行问题

### ISSUE THREAD

**Issue by CC52242** [jacksonjim/keil-assistant#35]
当前1.9.1版本中,C51项目编译时无法通过双击编译log中的报错提示来自动跳转到对应文件的对应代码行,
请问有计划实现这个功能吗?

**Comment by jacksonjim** [comment]
具体的是什么样错误，常见的都是可以的直接点击就可以跳转了，或是把你的log发过来看下，
