### ISSUE TITLE
切换分支，无法自动更新Preprocessor Symbols内的宏定义

### ISSUE THREAD

**Issue by DJZ1992** [jacksonjim/keil-assistant#36]
插件在切换分支时，不能把分支内定义的不同的宏定义更新到c_cpp_properties.json

**Comment by jacksonjim** [comment]
这个目前暂时不能关联相关的代码版本管理挂钩操作，目前可能需要你在git的相关挂钩相关动作更新下工程文件，或是重新打开下vscode的，才会读取更新，当前如果一直在定时刷新话，会带来性能问题，所以你先手动处理下会好些
