### ISSUE TITLE
我有一个STC32的工程没法正常打开

### ISSUE THREAD

**Issue by Xulijun180** [jacksonjim/keil-assistant#37]
STC32 的一个C251的工程不能正常打开，提示不是C51工程
![image](https://github.com/jacksonjim/keil-assistant/assets/100979711/a669e29f-6b7d-4c0f-b8fa-39ea31c45e78)

**Comment by jacksonjim** [comment]
你查看下这个工程文件配置，好像keil 4.x版本都有类似的情况，你目前使用的是keil 5.x 还是4.x

**Comment by jacksonjim** [comment]
targetDOM['TargetOption']['Target251'] 你查看下工程文件中是否有这个属性，如果没有会跳转C51的项目

**Comment by Alaye-Dong** [comment]
> STC32 的一个C251的工程不能正常打开，提示不是C51工程 ![image](https://private-user-images.githubusercontent.com/100979711/337569639-a669e29f-6b7d-4c0f-b8fa-39ea31c45e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzU5MzEsIm5iZiI6MTcxOTMzNTYzMSwicGF0aCI6Ii8xMDA5Nzk3MTEvMzM3NTY5NjM5LWE2NjllMjlmLTZiN2QtNGMwZi1iOGZhLTM5ZWEzMWM0NWU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNzEzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWM4NDU2NjYyMTE3YWM2ZDgxOTU0YWRjMTAzZWVmMjM5Yzk0ZWU2NmI0N2ExNDcxMjZhNmQwMjg4NWNhNjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uxzTdjvVQUwuCDQ0oqyErD5iLqbKNYYksIKAbQOn3-0)

![image](https://github.com/jacksonjim/keil-assistant/assets/123649770/cd9c7a53-7b6f-4606-9c2a-01c4ef58046f)
请检查是否插件的拓展设置Keil C251安装目录是否配置正确

**Comment by jacksonjim** [comment]
> > STC32 的一个C251的工程不能正常打开，提示不是C51工程 ![image](https://private-user-images.githubusercontent.com/100979711/337569639-a669e29f-6b7d-4c0f-b8fa-39ea31c45e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzU5MzEsIm5iZiI6MTcxOTMzNTYzMSwicGF0aCI6Ii8xMDA5Nzk3MTEvMzM3NTY5NjM5LWE2NjllMjlmLTZiN2QtNGMwZi1iOGZhLTM5ZWEzMWM0NWU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQxNzEzNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMWM4NDU2NjYyMTE3YWM2ZDgxOTU0YWRjMTAzZWVmMjM5Yzk0ZWU2NmI0N2ExNDcxMjZhNmQwMjg4NWNhNjI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uxzTdjvVQUwuCDQ0oqyErD5iLqbKNYYksIKAbQOn3-0)
> 
> ![image](https://private-user-images.githubusercontent.com/123649770/342835851-cd9c7a53-7b6f-4606-9c2a-01c4ef58046f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNzA1ODMsIm5iZiI6MTcxOTM3MDI4MywicGF0aCI6Ii8xMjM2NDk3NzAvMzQyODM1ODUxLWNkOWM3YTUzLTdiNmYtNDYwNi05YzJhLTAxYzRlZjU4MDQ2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQwMjUxMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzgxYmUwOWJjZDI0MGE1ZDVjOTI4NjRhMDAwNmZjNjE4OGY1M2IwMDljYmY0MGE5Y2M2OGUwZTMxYWEzMzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gJK44xHC1wGoa7wvhbrRamK5hEsn7NumV_-wtfNK9Vw) STC32为C251架构不是C51，请检查插件的拓展设置Keil C251安装目录是否配置正确

我清楚你STC32的架构，我也在使用这个MCU，我是让你检查项目的文件，不是这个配置信息，先确认下我上面提到的是否有这个，或你直接上传的项目文件过来

**Comment by Xulijun180** [comment]
[STC32G12K128.zip](https://github.com/user-attachments/files/16094298/STC32G12K128.zip)
这是我的整个工程，大佬您给看看吧

**Comment by Xulijun180** [comment]
问题解决了，谢谢大佬
