### ISSUE TITLE
点击打开项目按钮没有反应

### ISSUE THREAD

**Issue by pkhaituo** [jacksonjim/keil-assistant#38]
系统win7x64 vscode版本1.70.2
使用原仓库的版本正常，换到这个就不起作用

**Comment by jacksonjim** [comment]
![image](https://github.com/jacksonjim/keil-assistant/assets/3296695/a3863222-85f5-4843-b9c3-399d1ff9251d)
![image](https://github.com/jacksonjim/keil-assistant/assets/3296695/2c4715d0-3193-4ff0-9107-6b94ba6eaa28)

**Comment by pkhaituo** [comment]
试过了没成功

**Comment by jacksonjim** [comment]
> 试过了没成功

可能是你版本问题，你现在的vscode版本是什么，插件版本是什么

**Comment by jacksonjim** [comment]
版本: 1.91.0 (system setup)
提交: ea1445cc7016315d0f5728f8e8b12a45dc0a7286
日期: 2024-07-01T18:52:22.949Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.19045 
我这边的版本信息，一直都是正常的

**Comment by pkhaituo** [comment]
是我版本太旧了，装最新版就能正常了
