### ISSUE TITLE
建议：点击编译能自动保存文件

### ISSUE THREAD

**Issue by FeiyuCode** [jacksonjim/keil-assistant#4]
keil转过来不太习惯，经常文件没保存就点编译，然后出来的结果不对，还以为程序问题，找半天发现是没保存。
当然，这是我的原因。
还是希望能更新一下，点编译能自动保存。

**Comment by jacksonjim** [comment]
这个插件没做对应的自动保存文件功能，因为vscode已经支持自动保存文件功能，你可以直接开启这个就可以了
