### ISSUE TITLE
插件在Vscode中无法打开RTE环境中的文件

### ISSUE THREAD

**Issue by diffeet** [jacksonjim/keil-assistant#41]
![PixPin_2024-07-31_13-17-29](https://github.com/user-attachments/assets/83997cde-212c-40dd-9a85-e3f0187cbcde)
![PixPin_2024-07-31_13-18-17](https://github.com/user-attachments/assets/754eee05-a8d3-4ab5-a3cc-e2cb11c3f000)

可以手动添加RTE文件到c_cpp_properties.json吗？

**Comment by jacksonjim** [comment]
可以是可以的，RTE我测试没什么问题，你能帮确认下你所用的mcu系列是什么
或是你提供下项目的配置文件，我这边测试看下加载的路径，加入对应的mcu做处理

**Comment by jacksonjim** [comment]
新版本增加了自定义的引用头文件，在设置中有对应的设置你可以更新试试

**Comment by diffeet** [comment]
使用的是https://github.com/raspberrypi/CMSIS-RP2xxx-DFP/tree/main/example/mdk    这里项目里面的示例

**Comment by jacksonjim** [comment]
[keil-vscode-assistant-1.9.3.zip](https://github.com/user-attachments/files/16673573/keil-vscode-assistant-1.9.3.zip)
你先试试这个版本，试验没问题话，回复下再上传到市场那

**Comment by diffeet** [comment]
试了一下新版本还是打不开RTE环境，MDK版本5.37。还有一个问题，如果直接使用插件打开MDK工程会遇到下面这个情况，在终端使用命令行倒是可以打开工程。看了一下实际vscode安装文件夹中没有undefined。
![插件问题](https://github.com/user-attachments/assets/c2575e02-3e41-4a76-8f69-bd834dbcd1ff)

**Comment by jacksonjim** [comment]
这个要看下你具体的工程文件，我用你提供的demo没有出现类似的情况

**Comment by jacksonjim** [comment]
![image](https://github.com/user-attachments/assets/b2349e0f-ce89-4658-bc4a-e7d8b4b43546)
你这个提示说明的是路径不对，你可以看源码这里

**Comment by diffeet** [comment]
“test.zip”是测试过的一个工程，在三台电脑上的情况相同（系统同为WIN11），第一无法识别到RTE环境，第二就是在vscode中打开的时候会报错。
![错误二](https://github.com/user-attachments/assets/7b2d9fea-7d5f-4129-ad10-9234b600c046)

[test.zip](https://github.com/user-attachments/files/16686408/test.zip)

**Comment by jacksonjim** [comment]
![image](https://github.com/user-attachments/assets/6072c30d-5291-4192-8733-d3606ede45f3)

**Comment by jacksonjim** [comment]
> “test.zip”是测试过的一个工程，在三台电脑上的情况相同（系统同为WIN11），第一无法识别到RTE环境，第二就是在vscode中打开的时候会报错。 ![错误二](https://private-user-images.githubusercontent.com/33145410/359761350-7b2d9fea-7d5f-4129-ad10-9234b600c046.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMjIxNzksIm5iZiI6MTcyNDIyMTg3OSwicGF0aCI6Ii8zMzE0NTQxMC8zNTk3NjEzNTAtN2IyZDlmZWEtN2Q1Zi00MTI5LWFkMTAtOTIzNGI2MDBjMDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA2MzExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMWIzNDk4MzdhOGM5ODY5Y2Q3YTQ5NWRlODA3N2U4MTM2ZGRlMDdlYzYyNjFlZWZiYjU4NTljZWU1YTRjNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sLON62w-vq2OITKepiPibUDcJPGp7qIkrScR-A80AdI)
> 
> [test.zip](https://github.com/user-attachments/files/16686408/test.zip)

下载你的测试工程没问题的，直接可以打开的，也能正常识别，所以基本上是你们那的环境问题，你自己检查下哈

**Comment by jacksonjim** [comment]
大概看你可能是不是手动打开指定的项目文件，你直接用vscode打开
![image](https://github.com/user-attachments/assets/c9a930d2-4e4c-4310-97cd-045269046f7d)
这一级的目录就可以了，自动会扫描项目文件的，我这边什么不用修改，直接打开都是可以正常识别出来的

**Comment by jacksonjim** [comment]
大概目前知道你的操作方式了，基本上是我上面提前到的操作方式，你搞错了，你直接用vscode打开项目的目录即可，除非你项目文件在这个目录以外的位置才需要手动添加项目路径，你仔细查看使用说明

**Comment by diffeet** [comment]
两种都试了，没有办法加载使用RTE添加的CMSIS文件，是因为这些文件在arm-pack包安装位置不在项目文件夹里面的原因吗？
![打开MDK-ARM文件夹](https://github.com/user-attachments/assets/8b366227-d06d-449c-97c5-78ef2e9164df)
![打开整个工程的文件夹](https://github.com/user-attachments/assets/129bdbd3-08ae-4b0b-8d22-f32e03031132)

**Comment by jacksonjim** [comment]
> 两种都试了，没有办法加载使用RTE添加的CMSIS文件，是因为这些文件在arm-pack包安装位置不在项目文件夹里面的原因吗？ ![打开MDK-ARM文件夹](https://private-user-images.githubusercontent.com/33145410/360218244-8b366227-d06d-449c-97c5-78ef2e9164df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTIxMjEsIm5iZiI6MTcyNDI5MTgyMSwicGF0aCI6Ii8zMzE0NTQxMC8zNjAyMTgyNDQtOGIzNjYyMjctZDA2ZC00NDljLTk3YzUtNzhlZjJlOTE2NGRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxNTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwN2YyMjg4YzNjMDVlM2NmNzhlNmIzMzQxMjNmYmE4NDcyMDlkMjkyN2I1MTllN2JkMWVkN2IzMWI2MTc4YzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r3T7JH9J8EbD904pZ40-oyFt9Gon8zb--sdSker0p4w) ![打开整个工程的文件夹](https://private-user-images.githubusercontent.com/33145410/360218258-129bdbd3-08ae-4b0b-8d22-f32e03031132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTIxMjEsIm5iZiI6MTcyNDI5MTgyMSwicGF0aCI6Ii8zMzE0NTQxMC8zNjAyMTgyNTgtMTI5YmRiZDMtMDhhZS00YjBiLThkMjItZjMyZTAzMDMxMTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxNTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNGU2MmI1NTY1OTQ1ZGNlNDQwYjQxNDZjZGEwZjBhNzVlOGY5ZWZiNWE4MGFlZTQxYTBjMWNiNDdmNjE0MDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FiaxUMuDCrQWPrxxKAseALI_BVd0pEAFVbvQluFjGHQ)

不排除，有这种可能吧，目前你这个已经能正常识别了

**Comment by diffeet** [comment]
您那边可以在vscode里面看到RTE添加的CMSIS-DSP和RTX5的源文件吗？

**Comment by jacksonjim** [comment]
头文件是可以，但是源文件就没必要添加进来，一般来说会增加资源消耗的，目前也没有做.c的文件导入的

**Comment by jacksonjim** [comment]
另外识别的大多数是在下面的keil插件中的文件结构管理，也不会添加到vscode的文件管理
