### ISSUE TITLE
用F2快捷键重命名函数失败

### ISSUE THREAD

**Issue by MyZQL** [jacksonjim/keil-assistant#43]
可以正常使用Ctrl键进行索引，但无法用F2重命名函数，C/C++插件报错见下图。F2命名同一文件变量/函数正常。

![image](https://github.com/user-attachments/assets/8d9aac91-527d-46a8-8d6f-7224bd86a2cf)

**Comment by jacksonjim** [comment]
你这个错误应该是cpp的插件问题，这个插件不会修改原来的快捷方式的，你检查下设置是否有修改了对应的重命名快捷键

**Comment by MyZQL** [comment]
不是快捷键的问题哦，是无法使用Rename/Refactor重命名函数。

**Comment by jacksonjim** [comment]
> 不是快捷键的问题哦，是无法使用Rename/Refactor重命名函数。

那你检查下vscode配置情况，我这边一直都在使用这两个，另这个插件不会直接参与管理编码的部分，只是在编译和下载及识别keil的项目文件配置而已。你这个情况可以尝试卸载这个插件再看下具体的
