### ISSUE TITLE
读取keil5工程之后，工程宏defines会莫名其妙换行，导致宏失效

### ISSUE THREAD

**Issue by iamOJZ** [jacksonjim/keil-assistant#47]
![image](https://github.com/user-attachments/assets/b5b36db7-dcf1-473b-ad1d-a39b2112a599)
上面这个是源文件的宏，vscode导入后，“=”前后都被换行了，图如下：
![image](https://github.com/user-attachments/assets/77db4bc9-2898-4835-b108-3903fbbe83ba)
手动删去换行后可以正常一段时间，但是重新编译之后又乱了，大佬看下这个能不能修复下。

**Comment by jacksonjim** [comment]
这个misc control暂时没做匹配，下个版本适配，你先把这个宏调整到另一个宏定义上，效果是一致的
![image](https://github.com/user-attachments/assets/1f9f09c1-b1d1-4975-878f-82727be74916)

**Comment by jacksonjim** [comment]
![image](https://github.com/user-attachments/assets/b2d1db20-a75f-4951-a776-b115a14f13d2)
测试下本身不支持这个宏定义，但是你这个怎么什么出现这样，不是很明白，我复制你的这个定义方式，也没有出现这个，你是不是使用其它的插件

**Comment by iamOJZ** [comment]
大佬，这个问题我找到原因了，不是插件而是我keil工程本身的问题，细看xxx = xxx的“=”两边打多了空格；然后我看到插件中define解析逻辑，空格也是换行的条件之一，所以就造成了这个奇怪现象哈哈。最后还是感谢大佬抽空回issue。

**Comment by jacksonjim** [comment]
> 大佬，这个问题我找到原因了，不是插件而是我keil工程本身的问题，细看xxx = xxx的“=”两边打多了空格；然后我看到插件中define解析逻辑，空格也是换行的条件之一，所以就造成了这个奇怪现象哈哈。最后还是感谢大佬抽空回issue。

所有宏的定义不要放在miscControls，这个功能很少使用的，大部分是用来消除警告之类的，宏一般是在上面的Define上写的
