### ISSUE TITLE
导入STM32cubemx生成的工程后出现问题

### ISSUE THREAD

**Issue by huifeideteji** [jacksonjim/keil-assistant#48]
![image](https://github.com/user-attachments/assets/5418e5d0-09de-40fb-b85c-e1fa5c4b8ae5)
![image](https://github.com/user-attachments/assets/31654d8f-6ace-41d3-8802-5d3f38909223)
![image](https://github.com/user-attachments/assets/09b45d49-afdd-4c3a-ae7d-d856214285ff)
![image](https://github.com/user-attachments/assets/6191a7af-4ce4-4e28-a53a-9130c0be8d0c)

**Comment by jacksonjim** [comment]
需要用keil5打开下工程然后重新保存下就可以了，这个是因为生成的是keil 4版本的

**Comment by huifeideteji** [comment]
> 需要用keil5打开下工程然后重新保存下就可以了，这个是因为生成的是keil 4版本的

尝试过后对应的代码没发生变化

**Comment by jacksonjim** [comment]
你把工程发过来试试，我帮你验证下

**Comment by jacksonjim** [comment]
![image](https://github.com/user-attachments/assets/5b7528a4-ec0b-4b87-bba2-49ef9a1d241c)
![image](https://github.com/user-attachments/assets/faab0ae0-6cf4-46de-97a6-f253c48f01ee)
直接打开你的目录没问题的，也没提示出错

**Comment by jacksonjim** [comment]
![image](https://github.com/user-attachments/assets/afa00e31-f68a-4d27-9dbc-b0f4fcdc6505)

**Comment by jacksonjim** [comment]
![image](https://github.com/user-attachments/assets/1f117820-cca5-4da1-91a3-2de090bc3ce9)
另外你只需要直接打开这个目录即可，相对来说方便些，目前会扫描二级目录中带有keil的project文件

**Comment by huifeideteji** [comment]
那请问是否需要安装其他插件或者手动导入文件？刚刚用新项目试了一下，还是会红波浪。

**Comment by huifeideteji** [comment]
[settings.json](https://github.com/user-attachments/files/16843078/settings.json)
附上settings.json

**Comment by jacksonjim** [comment]
比较大可能是你keil环境配置吧，stm32的packs安装位置有没有问题，如果没有问题那些自动的includes可以不用的

**Comment by huifeideteji** [comment]
stm32的pack都是keil和stm32cubemx自动安装的，没有刻意去改。但是就是会有红波浪

**Comment by jacksonjim** [comment]
那就是你设置的KeilAssistant.Project.CustomIncludePaths 这个引起的吧，你可以清空这些设置的，

**Comment by huifeideteji** [comment]
奇怪的是删掉也不行

**Comment by jacksonjim** [comment]
你查看下
[c_cpp_properties.json](https://github.com/user-attachments/files/16845873/c_cpp_properties.json)
这个文件的配置信息如何

**Comment by jacksonjim** [comment]
只要是include路径中内容

**Comment by jacksonjim** [comment]
"KeilAssistant.Keil.HOME": {
        "MDK": "D:\\Program Files\\Keil_v5"
    },

**Comment by huifeideteji** [comment]
c_cpp_properties.json检查过了，除了其中一条include路径是C:\Users\admin\AppData\Local\Keil_v5\ARM\ARMCLANG\include外没有区别。
![image](https://github.com/user-attachments/assets/e491cacd-8fcc-424a-8f29-e0a61eea8881)
此处提供的俩配置似乎没区别
将配置更改如下仍旧存在红波浪线
![image](https://github.com/user-attachments/assets/c62e6f5e-4e51-4c79-b670-e93969bf1393)

**Comment by huifeideteji** [comment]
[settings.json](https://github.com/user-attachments/files/16847813/settings.json)
[c_cpp_properties.json](https://github.com/user-attachments/files/16847818/c_cpp_properties.json)
![image](https://github.com/user-attachments/assets/e4ab17af-1d8d-46f2-b3f8-f3a694b05f8a)

**Comment by jacksonjim** [comment]
你的这个情况，目前在我这边基本上不会出现，配置上看没问题，比较大可能是你的vscode 是否禁用了一些插件，你这样吧，尝试下重装下vscode，并删除vscode的配置信息，再重装安装下，再安装相关插件试试吧

**Comment by huifeideteji** [comment]
实在是奇怪，清空拓展文件夹后只安装C/C++ 简体中文 以及该项目，红波浪线确实消失了，怀疑可能是某些拓展间有冲突。但是编写代码时也无法提供补全建议了。附上原先拓展文件夹
![image](https://github.com/user-attachments/assets/1c971914-2633-425d-a895-03e1e26211fb)

**Comment by jacksonjim** [comment]
具体是哪些我也不好分析，这些超出技术范畴，你可以一个一个试试看

**Comment by huifeideteji** [comment]
那么该如何重新启用扩展的代码补全建议呢

**Comment by jacksonjim** [comment]
> 那么该如何重新启用扩展的代码补全建议呢

安装一些常用的插件就可以了，具体你要什么编程语言补全话，就安装对应的插件。建议你一步步安装一些常规的插件
