### ISSUE TITLE
运行命令 explorer.open 错误: command 'explorer.open' not found。这可能是由提交 explorer.open 的扩展引起的。

### ISSUE THREAD

**Issue by maomao23314** [jacksonjim/keil-assistant#49]
今天莫名其妙就没法打开项目了，工作区右边的加号也没了

**Comment by maomao23314** [comment]
必须安装另一个插件Keil Assistant才行，这俩不是一家吗？
安装Keil Assistant再卸载还是可以打开项目，重启vscode就不行了

**Comment by jacksonjim** [comment]
> 必须安装另一个插件Keil Assistant才行，这俩不是一家吗？ 安装Keil Assistant再卸载还是可以打开项目，重启vscode就不行了

不用安装这个也可以的，只是基于它的基础上做些功能升级和完善，但是最新版本需要升级到1.73+的vscode

**Comment by maomao23314** [comment]
不安装的话就无法打开项目！会显示explorer.open（还是意思差不多的指令）执行不了报错，打开文件按钮也是灰色的，VScode应该是最新的了

**Comment by jacksonjim** [comment]
> 不安装的话就无法打开项目！会显示explorer.open（还是意思差不多的指令）执行不了报错，打开文件按钮也是灰色的，VScode应该是最新的了

打开文件按钮为灰色话，基本上不是当前的插件引起，大概率是安装了其它插件，目前我们自己也使用暂时没有出现你这个情况为灰色的按钮，另外你查看readme的说明可以解决你打开项目的问题，我们按正常用vsocde打开对应的目录就可以了

**Comment by maomao23314** [comment]
莫名其妙就好了，先关闭问题吧
