### ISSUE TITLE
编译卡住，再次按编译按钮，“任务正在运行，请稍后，等其完成后再尝试”

### ISSUE THREAD

**Issue by Chuckmsg** [jacksonjim/keil-assistant#50]
![1725844910899](https://github.com/user-attachments/assets/defb6a87-73ea-46ce-a741-c2615c7a982d)
今天在公司电脑在首次编译卡住；前天在家中电脑首次可以编译

**Comment by Chuckmsg** [comment]
退回1.9.2版本也不行，这卡住一般是什么原因导致的

**Comment by jacksonjim** [comment]
线程还没跑完，等一会就可以了，正常点两次的时间间隔太短了，编译根据不同工程编译时间也是有 不同的

**Comment by Chuckmsg** [comment]
还是会卡住，编译时间过长了，一直在Start to Build target M1130，尝试卸载重装了vscode,keil，扩展只装需要的扩展，都不行

**Comment by Chuckmsg** [comment]
尝试了更改keil安装目录"MDK": "D:\\Keil_v5"，可以了

**Comment by Chuckmsg** [comment]
不好意思，找到问题了，不是安装路径的问题；是keil的权限设置的管理员权限，导致在vscode调用不了，可以来个提示
![微信截图_20240909173601](https://github.com/user-attachments/assets/fffd881e-b820-45c9-985f-9125cecf0415)

**Comment by jacksonjim** [comment]
这个提示目前好像不好监测，vscode没有提供类似的检测，插件不支持直接调用系统的接口
