### ISSUE TITLE
烧录功能输出中文路径乱码问题

### ISSUE THREAD

**Issue by TheBszk** [jacksonjim/keil-assistant#7]
很感谢有人维护项目，因为原插件快捷键不能正常使用所以找到了原作者的github，结果发现停止维护了。今天给别人推荐插件的时候发现了近似的插件，安装后体验了一番，发现快捷键bug已经修复，十分好用！但是还是发现了一个小问题，就是在**烧录发现输出中文路径会乱码**，在原插件上是没有这个问题的，望作者能修复一下

原插件：
![1](https://github.com/jacksonjim/keil-assistant/assets/78696827/03124028-f6e3-4379-976d-f1a4670340bd)

您维护的插件：
![2](https://github.com/jacksonjim/keil-assistant/assets/78696827/f98cec65-f31c-433d-ae76-8c9d43e1fb37)

**Comment by jacksonjim** [comment]
新版本已经修改，请下载更新再试试
